### ISSUE TITLE
Add ability to run without OpenAI/AzureAI key

### ISSUE THREAD

**Issue by kasparboelkjeldsen** [kasparboelkjeldsen/Knowit.Umbraco.Dictionoid#1]
It would be nice if Dictionoid could still function with all the other functionalities if no AI keys are setup.

Ie. we could still support key creation with 
```csharp
await Umbraco.Dictionoid(...
```
and then just not do the translations.

We can still do the nicer table view in the backoffice, expose the dictionary as an API etc. etc.

Basically, we should just disable the translation parts if there is no azure or open ai key, and not just crash as we do today.

**Comment by Amalie-Wowern** [comment]
I will look at this

**Comment by kasparboelkjeldsen** [comment]
fixed by [3](https://github.com/kasparboelkjeldsen/Knowit.Umbraco.Dictionoid/pull/3)
